default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["PG_USER"] %>
  password: <%= ENV["PG_PASSWORD"] %>
  host: localhost

development:
  <<: *default
  database: password_manager_development



test:
  <<: *default
  database: password_manager_test


production:
  database: password_manager_production
  username: password_manager
  password: <%= ENV["PASSWORD_MANAGER_DATABASE_PASSWORD"] %>
